/**
 * This file is auto-generated
 * Do not edit this file manually
 */
#include <string>
#include <vector>
#include <map>
#include <set>
#include <memory>
#include <easycc/Grammar.h>

namespace ecc{
    class GrammarFF : public Grammar {
    public:
        GrammarFF() {

/*FIRST_SET*/
/*FOLLOW_SET*/
/*PARSE_TABLE*/
        }
    };
}
