/**
 * This file is auto-generated
 * Do not edit this file manually
 */
#include <string>

namespace ecc{
    std::string lexicalConfigJSON = "/*LEXICAL_CONFIG*/";
    std::string lexicalErrorsJSON = "/*LEXICAL_ERRORS*/";
    std::string lexicalStateMachineJSON = "/*LEXICAL_STATE_MACHINE*/";
    std::string syntaxConfigJSON = "/*SYNTAX_CONFIG*/";
    std::string syntaxErrorsJSON = "/*SYNTAX_ERRORS*/";
    std::string syntaxGrammarJSON = "/*SYNTAX_GRAMMAR*/";
}
