/**
 * This file is auto-generated
 * Do not edit this file manually
 */
#include <string>
#include <easycc/tools/Base64.h>

namespace ecc{
    std::string lexicalConfigJSON = decode64("/*LEXICAL_CONFIG*/");
    std::string lexicalErrorsJSON = decode64("/*LEXICAL_ERRORS*/");
    std::string lexicalStateMachineJSON = decode64("/*LEXICAL_STATE_MACHINE*/");
    std::string syntaxErrorsJSON = decode64("/*SYNTAX_ERRORS*/");
    std::string syntaxGrammarJSON = decode64("/*SYNTAX_GRAMMAR*/");
}
