/**
 * This file is auto-generated
 * Do not edit this file manually
 */

#include <easycc/SyntaxMessages.h>

namespace ecc {
    void SyntaxMessages::staticContent() {
        /*DEFAULT_MESSAGE*/
        /*ERROR_MESSAGES*/
    }
}
