/**
 * This file is auto-generated
 * Do not edit this file manually
 */
#include <string>
#include <vector>
#include <map>
#include <set>
#include <memory>
#include <easycc/Grammar.h>

namespace ecc{

    void Grammar::staticContent() {
/*FIRST_SET*/
/*FOLLOW_SET*/
/*PARSE_TABLE*/
    }
}
